apiVersion: v1
kind: ConfigMap
metadata:
  name: ner-config
  namespace: ner-landslide
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  POSTGRES_HOST: "postgres-0.postgres.ner-landslide.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "ner_landslide"
  REDIS_HOST: "redis.ner-landslide.svc.cluster.local"
  REDIS_PORT: "6379"
  CELERY_BROKER_URL: "redis://redis.ner-landslide.svc.cluster.local:6379/0"
  S3_ENDPOINT: "s3.amazonaws.com"
  S3_BUCKET_RAW: "raw-data"
