apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ner-ingress
  namespace: ner-landslide
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api.ner-landslide.gov.in
    secretName: ner-tls-secret
  rules:
  - host: api.ner-landslide.gov.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-service
            port:
              number: 80
